import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { scoreReasons } from "./signals.js";

const safeName = (value) => value.replace(/[\\/:*?"<>|]/g, "-").slice(0, 80);
const yaml = (value) => JSON.stringify(value ?? "");

export function coinMarkdown(token, now = new Date()) {
  const reasons = scoreReasons(token);
  return `---
type: pump-coin
mint: ${yaml(token.mint)}
symbol: ${yaml(token.symbol)}
created: ${yaml(token.createdAt)}
updated: ${yaml(now.toISOString())}
status: ${yaml(token.status)}
narrative: ${yaml(token.narrative)}
momentum_score: ${token.momentum}
risk_score: ${token.risk}
risk_confidence: ${yaml(token.riskConfidence || (token.source === "demo" ? "synthetic" : "unverified"))}
market_cap_usd: ${Math.round(token.marketCap || 0)}
bonding_progress: ${Math.round(token.bondingProgress || 0)}
---

# ${token.name} (${token.symbol})

> Read-only research note. Scores are heuristics, not investment advice.

## Snapshot

- **Contract:** \`${token.mint}\`
- **Creator:** \`${token.creator || "unknown"}\`
- **Status:** ${token.status}
- **Narrative:** [[${token.narrative}]]
- **Market cap:** $${Math.round(token.marketCap || 0).toLocaleString("en-US")}
- **5m volume:** $${Math.round(token.volume5m || 0).toLocaleString("en-US")}
- **Bonding curve:** ${Math.round(token.bondingProgress || 0)}%
- **Pump.fun:** https://pump.fun/coin/${token.mint}
- **DEX Screener:** https://dexscreener.com/solana/${token.mint}

## Signal explanation

**Momentum ${token.momentum}/100:** ${reasons.momentum.join(", ")}.

**Risk ${Number.isFinite(token.risk) ? `${token.risk}/100` : "unverified"} (${reasons.riskConfidence}):** ${reasons.risk.join(", ")}.

## Research timeline

- ${now.toISOString()} — Note generated by Pump War Room.

## Human notes

- Add verified context, social evidence, and eventual outcome here.
`;
}

export async function exportCoin(vaultPath, token) {
  const coinDir = path.join(vaultPath, "Coins");
  const narrativeDir = path.join(vaultPath, "Narratives");
  await mkdir(coinDir, { recursive: true });
  await mkdir(narrativeDir, { recursive: true });
  const fileName = `${safeName(token.symbol)} - ${token.mint.slice(0, 8)}.md`;
  const coinPath = path.join(coinDir, fileName);
  await writeFile(coinPath, coinMarkdown(token), "utf8");
  const narrativePath = path.join(narrativeDir, `${safeName(token.narrative)}.md`);
  const narrative = `---\ntype: pump-narrative\nnarrative: ${yaml(token.narrative)}\n---\n\n# ${token.narrative}\n\n## Coins\n\n\`\`\`dataview\nTABLE symbol, momentum_score, risk_score, market_cap_usd\nFROM \"Coins\"\nWHERE narrative = ${yaml(token.narrative)}\nSORT momentum_score DESC\n\`\`\`\n`;
  await writeFile(narrativePath, narrative, "utf8");
  return coinPath;
}

export async function exportDaily(vaultPath, snapshot, now = new Date()) {
  const dir = path.join(vaultPath, "Daily Briefs");
  await mkdir(dir, { recursive: true });
  const date = now.toISOString().slice(0, 10);
  const pathName = path.join(dir, `${date} Pump Brief.md`);
  const movers = snapshot.tokens.slice(0, 7).map((t, i) => `${i + 1}. [[${t.symbol} - ${t.mint.slice(0, 8)}]] — momentum ${t.momentum}, risk ${t.risk}`).join("\n");
  const body = `---\ntype: pump-daily-brief\ndate: ${date}\nindexed: ${snapshot.stats.indexed}\nminted_today: ${snapshot.stats.mintedToday}\n---\n\n# Pump Brief — ${date}\n\n## Tape\n\n- Indexed: **${snapshot.stats.indexed.toLocaleString("en-US")}**\n- New today: **${snapshot.stats.mintedToday.toLocaleString("en-US")}**\n- Graduations: **${snapshot.stats.graduations.toLocaleString("en-US")}**\n\n## Movers\n\n${movers || "No signals yet."}\n\n## Analyst notes\n\n- Add conclusions after evidence review.\n`;
  await writeFile(pathName, body, "utf8");
  return pathName;
}
