import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { scoreReasons } from "./signals.js";

const safeName = (value) => value.replace(/[\\/:*?"<>|]/g, "-").slice(0, 80);
const yaml = (value) => JSON.stringify(value ?? "");
const finite = (value) => typeof value === "number" && Number.isFinite(value);
const integerOrUnknown = (value, suffix = "") => finite(value) ? `${Math.round(value).toLocaleString("en-US")}${suffix}` : "unknown";

export function coinMarkdown(token, now = new Date()) {
  const reasons = scoreReasons(token);
  return `---
type: pump-coin
mint: ${yaml(token.mint)}
symbol: ${yaml(token.symbol)}
created: ${yaml(token.createdAt)}
updated: ${yaml(now.toISOString())}
status: ${yaml(token.status)}
narrative: ${yaml(token.narrative)}
momentum_score: ${finite(token.momentum) ? Math.round(token.momentum) : "null"}
risk_score: null
risk_evidence: ${yaml(token.riskIdentity?.overallEvidence || token.riskConfidence || (token.source === "demo" ? "synthetic" : "unavailable"))}
market_cap_usd: ${finite(token.marketCap) ? Math.round(token.marketCap) : "null"}
bonding_progress: ${finite(token.bondingProgress) ? Math.round(token.bondingProgress) : "null"}
virtual_sol_reserve: ${finite(token.curveSol) ? token.curveSol : "null"}
---

# ${token.name} (${token.symbol})

> Read-only observational research, not investment advice or a safety claim.

## Snapshot

- **Contract:** \`${token.mint}\`
- **Creator:** \`${token.creator || "unknown"}\`
- **Deployer/user:** \`${token.deployer || "unknown"}\`
- **Status:** ${token.status}
- **Narrative:** [[${token.narrative}]]
- **Market cap:** ${finite(token.marketCap) ? `$${integerOrUnknown(token.marketCap)}` : "unknown"}
- **5m volume:** ${finite(token.volume5m) ? `$${integerOrUnknown(token.volume5m)}` : "unknown"}
- **Virtual SOL reserve:** ${finite(token.curveSol) ? `${token.curveSol.toLocaleString("en-US")} SOL` : "unknown"} (processed-feed observation; not curve progress or migration proof)
- **Pump.fun:** https://pump.fun/coin/${token.mint}
- **DEX Screener:** https://dexscreener.com/solana/${token.mint}

## Signal explanation

**Momentum ${finite(token.momentum) ? `${Math.round(token.momentum)}/100` : "unavailable"}:** ${reasons.momentum.join(", ")}.

**Risk probability withheld (${reasons.riskConfidence}):** ${reasons.risk.join(", ")}.

## Research timeline

- ${now.toISOString()} — Note generated by Pump War Room.

## Human notes

- Add source-attributed context and eventual outcome evidence here.
`;
}

export async function exportCoin(vaultPath, token) {
  const coinDir = path.join(vaultPath, "Coins");
  const narrativeDir = path.join(vaultPath, "Narratives");
  await mkdir(coinDir, { recursive: true });
  await mkdir(narrativeDir, { recursive: true });
  const fileName = `${safeName(token.symbol)} - ${token.mint.slice(0, 8)}.md`;
  const coinPath = path.join(coinDir, fileName);
  await writeFile(coinPath, coinMarkdown(token), "utf8");
  const narrativePath = path.join(narrativeDir, `${safeName(token.narrative)}.md`);
  const narrative = `---\ntype: pump-narrative\nnarrative: ${yaml(token.narrative)}\n---\n\n# ${token.narrative}\n\n## Coins\n\n\`\`\`dataview\nTABLE symbol, momentum_score, risk_score, market_cap_usd\nFROM \"Coins\"\nWHERE narrative = ${yaml(token.narrative)}\nSORT momentum_score DESC\n\`\`\`\n`;
  await writeFile(narrativePath, narrative, "utf8");
  return coinPath;
}

export async function exportDaily(vaultPath, snapshot, now = new Date()) {
  const dir = path.join(vaultPath, "Daily Briefs");
  await mkdir(dir, { recursive: true });
  const date = now.toISOString().slice(0, 10);
  const pathName = path.join(dir, `${date} Pump Brief.md`);
  const movers = snapshot.tokens.slice(0, 7).map((t, i) => `${i + 1}. [[${t.symbol} - ${t.mint.slice(0, 8)}]] — momentum ${finite(t.momentum) ? t.momentum : "unknown"}, risk probability withheld`).join("\n");
  const indexed = Number(snapshot.stats?.indexed || 0);
  const mintedToday = Number(snapshot.stats?.mintedToday || 0);
  const migrationsObserved = Number(snapshot.stats?.migrationsObserved || 0);
  const body = `---\ntype: pump-daily-brief\ndate: ${date}\nindexed: ${indexed}\nminted_today: ${mintedToday}\n---\n\n# Pump Brief — ${date}\n\n## Tape\n\n- Indexed: **${indexed.toLocaleString("en-US")}**\n- New today: **${mintedToday.toLocaleString("en-US")}**\n- Processed-feed migration observations: **${migrationsObserved.toLocaleString("en-US")}**\n\n## Movers\n\n${movers || "No signals yet."}\n\n## Analyst notes\n\n- Add conclusions after evidence review.\n`;
  await writeFile(pathName, body, "utf8");
  return pathName;
}
